### ISSUE TITLE
MethodsClient.chatPostMessage having problems with unsupported block type

### ISSUE THREAD

**Issue by bojandolinar** [seratch/jslack-maintenance-releases#30]
Slack's chat.postMessage REST method recently started returning blocks that include rich_text. This results in exception when MethodsClient.chatPostMessage is invoked:
```
com.google.gson.JsonParseException: Unsupported layout block type: rich_text
	at com.github.seratch.jslack.common.json.GsonLayoutBlockFactory.getLayoutClassInstance(GsonLayoutBlockFactory.java:38)
	at com.github.seratch.jslack.common.json.GsonLayoutBlockFactory.deserialize(GsonLayoutBlockFactory.java:19)
	at com.github.seratch.jslack.common.json.GsonLayoutBlockFactory.deserialize(GsonLayoutBlockFactory.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.google.gson.Gson.fromJson(Gson.java:848)
	at com.github.seratch.jslack.api.methods.impl.MethodsClientImpl.parseJsonResponseAndRunListeners(MethodsClientImpl.java:1758)
	at com.github.seratch.jslack.api.methods.impl.MethodsClientImpl.doPostFormWithToken(MethodsClientImpl.java:1731)
	at com.github.seratch.jslack.api.methods.impl.MethodsClientImpl.chatPostMessage(MethodsClientImpl.java:496)
```

This is not really a bug but would be nice to have more lenient method that would not try to parse (allegedly) undocumented content from Slack.

Others have problems, too (see [ticket](https://jira.atlassian.com/browse/JRASERVER-74410)).

**Comment by seratch** [comment]
Hi @bojandolinar, version 3.4 or newer no longer has this issue. See also: https://github.com/seratch/jslack-maintenance-releases/issues/10#issuecomment-629555853

If you are using jSlack in your code (or the package that you rely on), please upgrade its version to the latest. Also, I highly recommend migrating to Slack's official Java SDK (https://slack.dev/java-slack-sdk/), which is mostly compatible with jSlack except for the package names.

**Comment by bojandolinar** [comment]
Hey @seratch, thank you for prompt feedback. Upgrading the version was the first thing I tried but looks like I checked some weird repo because version 2.1.1 was the latest there. Now I see 3.4 is actually the latest. It works! :+1:

**Comment by bojandolinar** [comment]
Already fixed!

**Comment by seratch** [comment]
Great to hear!
